import { APP_NAME } from "./config"
import type { ErrorCode } from "./errors"
import type { ReviewTag } from "./review"

/**
 * Every piece of UI text lives here so a Bangla version can be added later.
 * Keep copy short and friendly.
 */
export const strings = {
  app: {
    name: APP_NAME,
    tagline: "Verified rides, both sides.",
    description: "Scan to start, scan to finish. Every trip verified by driver and passenger.",
  },

  common: {
    back: "Back",
    cancel: "Cancel",
    close: "Close",
    continue: "Continue",
    done: "Done",
    save: "Save",
    skip: "Skip",
    retry: "Try again",
    goHome: "Go home",
    optional: "Optional",
    today: "Today",
    yesterday: "Yesterday",
    copied: "Copied",
    copy: "Copy",
    you: "You",
  },

  duration: {
    seconds: (s: number) => `${s} sec`,
    minutes: (m: number) => `${m} min`,
    hours: (h: number) => `${h} h`,
    hoursMinutes: (h: number, m: string) => `${h} h ${m} min`,
  },

  roles: {
    driver: "Driver",
    passenger: "Passenger",
  },

  offline: "You’re offline",

  notConfigured: {
    title: "Supabase not configured",
    body: "Add SUPABASE_URL and SUPABASE_SECRET_KEY to .env.local (or your Vercel project settings), then restart the app.",
    hint: "See the README for setup steps.",
  },

  errorPage: {
    title: "Something went wrong",
    body: "Please try again. If it keeps happening, restart the app.",
  },

  notFound: {
    title: "Nothing here",
    body: "This page doesn’t exist or has moved.",
  },

  welcome: {
    title: `Welcome to ${APP_NAME}`,
    subtitle: "Scan to start, scan to finish. How will you ride?",
    roleQuestion: "Choose one",
    driverCard: {
      title: "I’m a driver",
      body: "Start trips by scanning your passenger’s pass.",
    },
    passengerCard: {
      title: "I’m a passenger",
      body: "Show your pass to ride, scan to finish.",
    },
    restoreLink: "Already registered?",
    restoreLinkAction: "Enter your code",
    step: (n: number, total: number) => `Step ${n} of ${total}`,
    detailsTitle: {
      driver: "You and your car",
      passenger: "About you",
    },
    detailsSubtitle: "Shown to the other person on each trip.",
    name: "Your name",
    namePlaceholder: "e.g. Rahim Uddin",
    phone: "Phone",
    phonePlaceholder: "e.g. 01711 000000",
    vehicle: "Vehicle number",
    vehiclePlaceholder: "e.g. DHAKA METRO GA 11-2345",
    vehicleHint: "Switched cars? You can change this anytime.",
    idNumber: "ID number",
    idNumberPlaceholder: "e.g. employee ID",
    create: "Create my pass",
    doneTitle: "You’re all set",
    doneBody: {
      driver: "This is your driver QR. Passengers scan it when they get off.",
      passenger: "This is your Ride Pass. Show it to your driver when you get in.",
    },
    doneCta: {
      driver: "Go to my trips",
      passenger: "Go to my pass",
    },
    continueCta: "Continue",
  },

  restore: {
    title: "Enter your code",
    body: "It’s the 6-character code under your QR, like K7M-2QX.",
    label: "Your code",
    submit: "Restore my pass",
    welcomeBack: (name: string) => `Welcome back, ${name}`,
  },

  codeInput: {
    placeholder: "K7M-2QX",
    lookalikes: "Codes never use 0, O, 1, I or L. Check those characters.",
    incomplete: "Codes have 6 letters and numbers.",
  },

  header: {
    profile: "Your profile",
    changeVehicle: "Change vehicle",
  },

  pass: {
    rideLabel: "Ride Pass",
    driverLabel: "Driver QR",
    name: "Name",
    idNumber: "ID",
    phone: "Phone",
    vehicle: "Vehicle",
    noId: "—",
    showDriver: "Show this to your driver",
    driverScanHint: "Passenger scans this when they get off",
    tapToEnlarge: "Tap QR to enlarge",
    tapToClose: "Tap anywhere to close",
    qrAlt: (code: string) => `QR code for ${code}`,
  },

  passenger: {
    greeting: (name: string) => `Hi, ${name}`,
    passSubtitle: "Your Ride Pass",
    waiting: "Waiting for your driver to start the trip",
    onTripTitle: "Trip in progress",
    onTrip: "On trip",
    tripStartedToast: "Your trip has started",
    driver: "Driver",
    started: "Started",
    elapsed: "Time on trip",
    arrivedCta: "I’ve arrived — scan driver QR",
    arrivedHint: "At your stop? Scan the QR on the driver’s phone or in the car.",
  },

  driver: {
    greeting: (name: string) => `Hi, ${name}`,
    startCta: "Start trip — scan passenger QR",
    activeTitle: "On trip now",
    tripCompletedToast: (name: string) => `Trip with ${name} completed`,
    started: (time: string) => `Started ${time}`,
    emptyTitle: "No active trips",
    emptyBody: "Tap Start trip and scan your passenger’s Ride Pass.",
    myQrTitle: "My QR",
    myQrBody: "Print it and keep it in your car.",
    vehicleUpdated: "Vehicle updated",
    vehicleSheetTitle: "Change vehicle",
    vehicleSheetBody: "New trips will use this number.",
    noVehicle: "Add vehicle",
  },

  myQr: {
    title: "My QR",
    subtitle: "Passengers scan this to end their trip.",
    print: "Print",
    printHeading: "End your trip here",
    printBody: "Passengers: scan this QR when you get off.",
  },

  profile: {
    title: "Your profile",
    code: "Your code",
    codeHint: "Use it to restore your pass on a new phone.",
    phone: "Phone",
    idNumber: "ID number",
    vehicle: "Vehicle",
    notSet: "Not set",
    myQr: "My QR & print",
    reset: "Reset this device",
    resetTitle: "Reset this device?",
    resetBody: (code: string) =>
      `This removes your pass from this phone. You can get it back anytime with your code ${code}.`,
    resetConfirm: "Yes, reset",
    resetDone: "This phone has been reset",
  },

  recent: {
    title: "Recent trips",
    emptyTitle: "No trips yet",
    emptyBody: "Your trips will show up here.",
    active: "Active",
    completed: "Completed",
    tripNo: (n: number) => `Trip #${n}`,
    with: (name: string) => name,
  },

  camera: {
    allowTitle: "Allow camera",
    allowBody: "We use the camera only to scan QR codes and to photo the dashboard. Nothing is recorded.",
    allowCta: "Allow camera",
    starting: "Starting camera…",
    deniedTitle: "Camera is blocked",
    deniedBody: "Turn on camera access for this site, then try again.",
    unavailableTitle: "Camera not available",
    unavailableBody: "We couldn’t start a camera on this device.",
    busyTitle: "Camera is busy",
    busyBody: "Another app may be using the camera. Close it and try again.",
    insecureTitle: "Camera needs a secure link",
    insecureBody: "Open the app with an https:// address to use the camera.",
    chromeSteps: {
      title: "Chrome on Android",
      steps: [
        "Tap the icon left of the address bar",
        "Tap Permissions → Camera → Allow",
        "Come back and tap Try again",
      ],
    },
    safariSteps: {
      title: "Safari on iPhone",
      steps: [
        "Tap aA in the address bar",
        "Tap Website Settings → Camera → Allow",
        "Come back and tap Try again",
      ],
    },
    inAppHint: "Opened from Messenger or WhatsApp? Open this link in Chrome or Safari instead.",
    retry: "Try again",
    torchOn: "Turn on flashlight",
    torchOff: "Turn off flashlight",
  },

  scanner: {
    titleDriver: "Scan passenger’s Ride Pass",
    titlePassenger: "Scan the driver’s QR",
    hint: "Fit the QR inside the frame",
    typeCode: "Type the code instead",
    manualTitle: "Type the code",
    manualBodyDriver: "It’s under the QR on the passenger’s Ride Pass.",
    manualBodyPassenger: "It’s under the QR on the driver’s phone or card.",
    manualSubmit: "Continue",
    notACode: `That QR isn’t a ${APP_NAME} code.`,
    scanAgain: "Scan again",
    checking: "Checking…",
  },

  start: {
    title: "Start trip",
    steps: ["Scan", "Photo", "Start"],
    verified: "Verified",
    passenger: "Passenger",
    photoTitle: "Dashboard photo",
    photoBody: "Show the steering and odometer.",
    photoCta: "Take photo",
    photoRetake: "Retake",
    photoUse: "Use photo",
    photoGuide: "Fit the dashboard and odometer in the frame",
    photoCapture: "Take photo",
    photoFallback: "Open camera",
    photoFallbackHint: "Live camera unavailable. Use your phone’s camera instead.",
    startTime: "Start time",
    startTimeNote: "Recorded when you tap Start",
    startCta: "Start journey",
    needPhoto: "Take the dashboard photo to continue",
    uploading: "Uploading photo…",
    uploadFailed: "Upload failed. Your photo is kept. Tap Try again.",
    successTitle: "Trip started",
    successBody: (name: string) => `Have a safe ride with ${name}.`,
    successCta: "Back to trips",
    alreadyStarted: "This trip is already running.",
  },

  end: {
    title: "End trip",
    confirmTitle: "At your stop?",
    confirmBody: (driver: string) => `End your trip with ${driver}?`,
    confirmCta: "End trip",
    ending: "Ending trip…",
    endedToast: "Trip completed",
  },

  receipt: {
    title: "Trip complete",
    tripNo: (n: number) => `Trip #${n}`,
    verified: "Verified by both",
    driver: "Driver",
    passenger: "Passenger",
    vehicle: "Vehicle",
    start: "Start",
    end: "End",
    duration: "Duration",
    date: "Date",
    status: "Status",
    inProgress: "In progress",
    completed: "Completed",
    photo: "Dashboard at start",
    photoOpen: "Tap to view full screen",
    photoMissing: "Photo unavailable",
  },

  review: {
    title: "How was your ride?",
    subtitle: (driver: string) => `Rate your trip with ${driver}`,
    ratingLabels: ["", "Terrible", "Bad", "Okay", "Good", "Great"] as const,
    starLabel: (n: number) => `${n} star${n === 1 ? "" : "s"}`,
    tagsTitle: {
      positive: "What went well?",
      negative: "What went wrong?",
    },
    commentLabel: "Anything else?",
    commentPlaceholder: "Optional comment",
    submit: "Submit review",
    skip: "Skip for now",
    thanksTitle: "Thanks for your review",
    thanksBody: "It helps keep rides safe and honest.",
    rateLater: "Rate this trip",
    rated: "Your rating",
    tags: {
      safe_driving: "Safe driving",
      on_time: "On time",
      clean_car: "Clean car",
      polite: "Polite",
      smooth_ride: "Smooth ride",
      late: "Late",
      rash_driving: "Rash driving",
      dirty_car: "Dirty car",
      rude: "Rude",
      wrong_route: "Wrong route",
      ac_not_working: "AC not working",
    } satisfies Record<ReviewTag, string>,
  },

  trip: {
    title: "Trip details",
    privateReview: "Reviews are private to passengers.",
  },

  q: {
    title: `${APP_NAME} QR`,
    unknownTitle: "QR not recognised",
    unknownBody: "This code isn’t registered. Check it and try again.",
    ownPassTitle: "This is your Ride Pass",
    ownPassBody: "Show it to your driver when you get in.",
    ownDriverTitle: "This is your driver QR",
    ownDriverBody: "Passengers scan it when they get off.",
    passengerViewsPassengerTitle: "That’s a passenger Ride Pass",
    passengerViewsPassengerBody: "To end a trip, scan the driver’s QR.",
    driverViewsDriverTitle: "That’s a driver QR",
    driverViewsDriverBody: "Ask the passenger to show their Ride Pass.",
    noTripTitle: "You’re not on a trip",
    noTripBody: "This is a driver QR. Scan it at the end of your trip.",
    wrongDriverTitle: "Not your driver",
    wrongDriverBody: "This QR belongs to a different driver. Scan the QR in the car you’re in.",
    openApp: `Open ${APP_NAME}`,
  },

  errors: {
    network: "Can’t reach the server. Check your connection.",
    server_error: "Something went wrong. Please try again.",
    not_configured: "The app isn’t connected to its database yet.",
    not_registered: "Set up this phone first.",
    already_registered: "This phone already has a pass.",
    wrong_role: "That isn’t available for your role.",
    invalid_input: "Please check the details and try again.",
    name_required: "Please enter your name.",
    vehicle_required: "Please enter your vehicle number.",
    code_invalid: "That code doesn’t look right. It has 6 letters and numbers, like K7M-2QX.",
    code_not_found: "We couldn’t find that code. Check it and try again.",
    expected_passenger_code: "That’s a driver QR. Ask the passenger to show their Ride Pass.",
    expected_driver_code: "That’s a passenger Ride Pass. Scan the driver’s QR instead.",
    own_code: "That’s your own QR.",
    passenger_busy: "This passenger is already on another trip.",
    photo_required: "Take the dashboard photo first.",
    photo_too_large: "That photo is too large. Please retake it.",
    upload_failed: "The photo didn’t upload. Check your connection and try again.",
    no_active_trip: "You’re not on a trip right now.",
    wrong_driver: "This QR belongs to a different driver. Scan the QR in the car you’re in.",
    trip_not_found: "We couldn’t find that trip.",
    trip_not_completed: "This trip hasn’t ended yet.",
    already_reviewed: "You’ve already rated this trip. Thanks!",
    rating_required: "Tap a star to rate your trip.",
  } satisfies Record<ErrorCode, string>,
} as const

export type Strings = typeof strings
